### ISSUE TITLE
Unit tests fail due to out of date assertion msg files

### ISSUE THREAD

**Issue by dellgreen** [jtidy/jtidy#2]
Seems that the test assertions message files contain nodes no longer produced by the library.
Currently working on a fix

**Comment by wltjr** [comment]
Ok sounds good, thanks for looking into all this and working on fixes. Even though I do not use, I hate to see stale code still in use. Long as its used by JMeter and others. Should get things back into current working state. Happy to help with what I can. Though since I do not use, seems most work will be left to you or others...

**Comment by haumacher** [comment]
Removed outdated messages in 9913a6e57e0c4062999d3500f0d39b80324fd2f6 but this is only part of the problem. 119 failures and 2 errors remain.

**Comment by haumacher** [comment]
Has been fixed together with #4.
